"use strict";

const STORAGE_KEYS = { questions: "ds_kentei_app_questions_v1", progress: "ds_kentei_app_progress_v1" };
const state = { questions: null, progress: null, view: "top", session: null, history: { category: "all", status: "all", sort: "id" }, storage: { questionsMissing: false, progressMissing: false } };
const views = Object.fromEntries(["top", "practice", "summary", "textbook", "history", "data"].map((name) => [name, document.querySelector(`#${name}-view`)]));

function initialProgress() { return { version: 1, records: {}, categoryStatus: {}, resumePointer: {} }; }
function saveProgress() { localStorage.setItem(STORAGE_KEYS.progress, JSON.stringify(state.progress)); }
function restoreState() {
  const cachedQuestions = localStorage.getItem(STORAGE_KEYS.questions);
  state.storage.questionsMissing = !cachedQuestions;
  if (cachedQuestions) try { const parsed = JSON.parse(cachedQuestions); if (Array.isArray(parsed.categories)) state.questions = parsed; else throw Error(); } catch (_) { localStorage.removeItem(STORAGE_KEYS.questions); state.storage.questionsMissing = true; }
  const cachedProgress = localStorage.getItem(STORAGE_KEYS.progress);
  state.storage.progressMissing = !cachedProgress;
  if (cachedProgress) try { state.progress = JSON.parse(cachedProgress); } catch (_) { state.progress = initialProgress(); state.storage.progressMissing = true; } else state.progress = initialProgress();
  state.progress.records ||= {}; state.progress.categoryStatus ||= {}; state.progress.resumePointer ||= {}; state.progress.version ||= 1; saveProgress();
}
function categories() { return state.questions?.categories || []; }
function allQuestions() { return categories().flatMap((category) => category.questions || []); }
function sortedQuestions(category) { return [...(category.questions || [])].sort((a, b) => a.id - b.id); }
function categoryIndex(category) { return categories().indexOf(category) + 1; }
function findQuestion(id) { return allQuestions().find((question) => question.id === id); }
function categoryFor(question) { return categories().find((category) => (category.questions || []).some((candidate) => candidate.id === question.id)); }
function percent(n, total) { return total === 0 ? "—" : `${Math.round(n / total * 100)}%`; }
function statusLabel(status) { return ({ not_started: "未着手", in_progress: "進行中", completed: "完了" })[status]; }
function categoryStatus(category) { return state.progress.categoryStatus[category.categoryId] || "not_started"; }
function metrics(questionList) { const answered = questionList.filter((q) => state.progress.records[String(q.id)]).length; const correct = questionList.filter((q) => state.progress.records[String(q.id)]?.lastResult === "correct").length; return { answered, total: questionList.length, rate: percent(correct, questionList.length) }; }
function formatDate(iso) { if (!iso || Number.isNaN(new Date(iso).getTime())) return null; const d = new Date(iso); const p = (n) => String(n).padStart(2, "0"); return `${d.getFullYear()}/${p(d.getMonth()+1)}/${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`; }

function setView(view) { state.view = view; Object.entries(views).forEach(([name, element]) => element.hidden = name !== view); ({ top: renderTop, practice: renderPractice, summary: renderSummary, textbook: renderTextbook, history: renderHistory, data: renderData })[view](); }
function renderTop() {
  const questions = allQuestions(), overall = metrics(questions), weak = questions.filter((q) => state.progress.records[String(q.id)]?.lastResult === "incorrect"), date = formatDate(state.progress.lastExportedAt);
  const meta = state.questions?.meta;
  views.top.innerHTML = `<div class="top-header"><h1 id="top-title">DS検定学習</h1><button class="text-link" id="history">解答履歴</button></div>${meta?.exam || meta?.syllabusVersion ? `<p class="metadata">${[meta.exam,meta.syllabusVersion].filter(Boolean).join("｜")}</p>` : ""}<div class="summary"><p class="summary-line">解答済 ${overall.answered}/${overall.total}問 ／ 全体正答率 ${overall.rate}</p><p class="${date ? "" : "export-status"}">最終エクスポート：${date || "未エクスポート"}</p></div><div class="actions"><button id="data">データ管理</button><button id="weak" ${weak.length ? "" : "disabled"}>苦手問題を復習する（全分野横断）</button></div><p class="help-text" ${weak.length ? "hidden" : ""}>苦手問題はありません</p><div id="guidance"></div><div id="textbook-entry"></div><div id="content"></div>`;
  views.top.querySelector("#data").onclick = () => setView("data"); views.top.querySelector("#history").onclick = () => openHistory(); views.top.querySelector("#weak").onclick = () => startReview(weak);
  if (state.storage.questionsMissing || state.storage.progressMissing) views.top.querySelector("#guidance").innerHTML = `<div class="notice">${state.storage.questionsMissing ? "<p>問題データを読み込んでください。</p>" : ""}${state.storage.progressMissing ? "<p>学習記録を復元してください。</p>" : ""}</div>`;
  const content = views.top.querySelector("#content");
  if (!state.questions) { content.innerHTML = `<div class="notice"><h2>問題データがありません</h2><p class="help-text">問題データ（questions.json）を読み込んでください。</p><label class="file-button">問題データを読み込む<input id="question-file" type="file" accept="application/json,.json"></label><p id="error" class="error-message" role="alert"></p></div>`; content.querySelector("#question-file").onchange = handleQuestionFile; return; }
  const textbookEntry = views.top.querySelector("#textbook-entry");
  textbookEntry.className = "textbook-entry";
  textbookEntry.innerHTML = `<h2>教科書モードで読む</h2><p class="help-text">解答・解説を見ながら、問題を通しで読めます（採点なし）</p><div class="textbook-entry-list"></div>`;
  const textbookList = textbookEntry.querySelector(".textbook-entry-list");
  categories().forEach((category) => { const button = document.createElement("button"); button.type = "button"; button.textContent = `分野${categoryIndex(category)}　${category.title}`; button.onclick = () => openTextbook(category); textbookList.append(button); });
  const list = document.createElement("div"); list.className = "category-list"; categories().forEach((category) => list.append(categoryCard(category))); content.append(list);
}
function categoryCard(category) {
  const status = categoryStatus(category), score = metrics(category.questions || []), incorrect = (category.questions || []).some((q) => state.progress.records[String(q.id)]?.lastResult === "incorrect"), card = document.createElement("article"); card.className = "category-card";
  card.innerHTML = `<div class="card-heading"><p class="category-title">分野${categoryIndex(category)}　${category.title}</p><span class="badge ${status.replace("_", "-")}">${statusLabel(status)}</span></div><p class="metrics">解答済 ${score.answered}/${score.total}問 ・ 正答率 ${score.rate}</p><div class="category-actions"></div>`;
  const actions = card.querySelector(".category-actions"), button = (label, fn, secondary=false, disabled=false) => { const b=document.createElement("button"); b.textContent=label; b.disabled=disabled; if(secondary)b.className="secondary"; b.onclick=fn; actions.append(b); };
  if (status === "not_started") button("演習を始める", () => startPractice(category, false));
  if (status === "in_progress") { button("続きから再開", () => startPractice(category, true)); button("最初から解き直す", () => startPractice(category, false), true); }
  if (status === "completed") { button("もう一度解く", () => startPractice(category, false)); button("間違えた問題だけ復習", () => startReview(sortedQuestions(category).filter((q) => state.progress.records[String(q.id)]?.lastResult === "incorrect")), true, !incorrect); }
  button("教科書で読む", () => openTextbook(category), true);
  return card;
}

function openTextbook(category) { state.session = { mode: "textbook", category }; setView("textbook"); }
function renderTextbook() {
  const category = state.session.category, questions = sortedQuestions(category), index = categories().indexOf(category), next = categories()[index + 1];
  views.textbook.innerHTML = `<div class="textbook-header"><h1>分野${categoryIndex(category)}　${category.title}</h1><button class="text-link" id="textbook-back">トップに戻る</button></div><nav class="textbook-toc" aria-label="問題目次"></nav><div class="textbook-list"></div><div class="textbook-footer"><button class="secondary" id="textbook-bottom-back">トップに戻る</button>${next ? '<button id="textbook-next">次の分野を読む</button>' : ""}</div>`;
  views.textbook.querySelector("#textbook-back").onclick = () => setView("top");
  views.textbook.querySelector("#textbook-bottom-back").onclick = () => setView("top");
  if (next) views.textbook.querySelector("#textbook-next").onclick = () => openTextbook(next);
  const toc = views.textbook.querySelector(".textbook-toc"), list = views.textbook.querySelector(".textbook-list");
  questions.forEach((question) => {
    const anchorId = `textbook-question-${question.id}`, link = document.createElement("a"); link.href = `#${anchorId}`; link.textContent = question.id; toc.append(link);
    const article = document.createElement("article"); article.className = "textbook-question"; article.id = anchorId;
    const number = document.createElement("p"); number.className = "textbook-question-number"; number.textContent = `問${question.id}`;
    const text = document.createElement("p"); text.className = "question-text"; text.textContent = question.text;
    const choices = document.createElement("div"); choices.className = "choice-list";
    question.choices.forEach((choice) => { const item = document.createElement("p"); item.className = "choice-button textbook-choice"; item.textContent = `${choice.key}　${choice.text}`; if (choice.key === question.answer) item.classList.add("correct-choice"); choices.append(item); });
    const explanation = document.createElement("div"); explanation.className = "textbook-explanation"; explanation.innerHTML = "<strong>解説</strong>"; const explanationText = document.createElement("p"); explanationText.textContent = question.explanation; explanation.append(explanationText);
    const divider = document.createElement("hr"); article.append(number, text, choices, explanation, divider); list.append(article);
  });
}

function startPractice(category, resume) { const questions = sortedQuestions(category), pointer = state.progress.resumePointer[category.categoryId], index = resume ? questions.findIndex((q) => q.id === pointer) : -1; state.session = { mode:"practice", category, questions, index: index >= 0 ? index : 0, selected:null, answered:false, sessionResults:[] }; setView("practice"); }
function startReview(questionList) { state.session = { mode:"review", category:null, questions:[...questionList].sort((a,b)=>a.id-b.id), index:0, selected:null, answered:false, sessionResults:[] }; setView("practice"); }
function renderPractice() {
  const s=state.session, q=s.questions[s.index], final=s.index===s.questions.length-1, heading=s.mode === "review" ? `復習モード ／ 問 ${s.index+1} / ${s.questions.length}` : `分野${categoryIndex(s.category)} ／ 問 ${s.index+1} / ${s.questions.length}`;
  views.practice.innerHTML=`<p class="practice-progress">${heading}</p><button class="text-link" id="interrupt">中断してトップへ戻る</button><article class="question-card"><p id="result" class="result-label" ${s.answered?"":"hidden"}></p><p class="question-text"></p><div id="choices" class="choice-list"></div><div id="explanation" class="explanation" ${s.answered?"":"hidden"}></div></article><div class="practice-action"><button id="action" ${s.selected?"":"disabled"}>${s.answered ? final ? "結果を見る" : "次の問題へ" : "解答する"}</button></div>`;
  views.practice.querySelector(".question-text").textContent=q.text; const choices=views.practice.querySelector("#choices"); q.choices.forEach((choice)=>{ const b=document.createElement("button"); b.className="choice-button"; b.textContent=`${choice.key}　${choice.text}`; b.disabled=s.answered; b.setAttribute("aria-pressed",String(s.selected===choice.key)); if(s.selected===choice.key)b.classList.add("selected"); if(s.answered&&choice.key===q.answer)b.classList.add("correct-choice"); if(s.answered&&choice.key===s.selected&&choice.key!==q.answer)b.classList.add("incorrect-choice"); b.onclick=()=>{s.selected=choice.key;renderPractice();}; choices.append(b); });
  views.practice.querySelector("#interrupt").onclick=()=>setView("top"); views.practice.querySelector("#action").onclick=()=>{ if(!s.answered) submitAnswer(); else if(final) finishSession(); else {s.index++;s.selected=null;s.answered=false;renderPractice();} };
  if(s.answered){const correct=s.selected===q.answer, result=views.practice.querySelector("#result"); result.textContent=correct?"正解":"不正解";result.classList.add(correct?"result-correct":"result-incorrect");views.practice.querySelector("#explanation").textContent=q.explanation;}
}
function submitAnswer() { const s=state.session,q=s.questions[s.index],correct=s.selected===q.answer,id=String(q.id),record=state.progress.records[id]||{attempts:0,lastResult:null,history:[]}; record.history.push({timestamp:new Date().toISOString(),selected:s.selected,correct});record.attempts=record.history.length;record.lastResult=correct?"correct":"incorrect";state.progress.records[id]=record;
  if(s.mode==="practice"){state.progress.categoryStatus[s.category.categoryId]="in_progress";const next=s.questions[s.index+1];if(next)state.progress.resumePointer[s.category.categoryId]=next.id;else delete state.progress.resumePointer[s.category.categoryId];} saveProgress();s.sessionResults.push({id:q.id,selected:s.selected,correct});s.answered=true;renderPractice(); }
function finishSession() { const s=state.session;if(s.mode==="practice"){state.progress.categoryStatus[s.category.categoryId]="completed";delete state.progress.resumePointer[s.category.categoryId];saveProgress();}setView("summary"); }
function renderSummary() { const s=state.session, correct=s.sessionResults.filter((r)=>r.correct).length, errors=s.sessionResults.filter((r)=>!r.correct), review=s.mode==="review", title=review ? "復習モード 演習結果" : `分野${categoryIndex(s.category)} 演習結果`; views.summary.innerHTML=`<h1>${title}</h1><div class="summary"><p class="summary-line">今回のセッションの成績：${s.sessionResults.length}問中 ${correct}問正解（${percent(correct,s.sessionResults.length)}）</p></div><div id="errors"></div><div class="actions" id="actions"></div>`;
  const errorBox=views.summary.querySelector("#errors"); if(!errors.length)errorBox.innerHTML='<p class="notice">全問正解です</p>';else {const list=document.createElement("div");list.className="incorrect-list";errors.forEach((r)=>{const q=findQuestion(r.id),item=document.createElement("details");item.className="incorrect-item";item.innerHTML=`<summary>${q.text.slice(0,40)}…　あなたの解答：${r.selected}／正解：${q.answer}</summary><p class="accordion-question"></p><p class="accordion-explanation"></p>`;item.querySelector(".accordion-question").textContent=q.text;item.querySelector(".accordion-explanation").textContent=q.explanation;list.append(item);});errorBox.append(list);}
  const actions=views.summary.querySelector("#actions"), add=(label,fn,disabled=false,secondary=false)=>{const b=document.createElement("button");b.textContent=label;b.disabled=disabled;if(secondary)b.className="secondary";b.onclick=fn;actions.append(b);};
  if(review){const remaining=s.questions.filter((q)=>state.progress.records[String(q.id)]?.lastResult==="incorrect");add("まだ間違えている問題をもう一度復習する",()=>startReview(remaining),!remaining.length);}else{add("間違えた問題だけ復習する",()=>startReview(errors.map((r)=>findQuestion(r.id))),!errors.length);const i=categories().indexOf(s.category);if(i<categories().length-1)add("次の分野へ進む",()=>startPractice(categories()[i+1],false));}add("トップに戻る",()=>setView("top"),false,true);
}

function openHistory(category="all") { state.history={category,status:"all",sort:"id"};setView("history"); }
function renderHistory() { if(!state.questions){views.history.innerHTML='<h1 id="history-title">解答履歴</h1><p class="notice">問題データを読み込むと解答履歴を表示できます。</p><button class="secondary" id="back">トップに戻る</button>';views.history.querySelector("#back").onclick=()=>setView("top");return;}
  views.history.innerHTML=`<div class="top-header"><h1 id="history-title">解答履歴</h1><button class="text-link" id="back">トップに戻る</button></div><div class="history-filters"><label>分野<select id="category"><option value="all">すべての分野</option></select></label><label>ステータス<select id="status"><option value="all">すべて</option><option value="unanswered">未解答</option><option value="correct">直近正解</option><option value="incorrect">直近不正解</option></select></label><label>並び替え<select id="sort"><option value="id">問題番号順</option><option value="attempts-desc">解答回数が多い順</option><option value="attempts-asc">解答回数が少ない順</option></select></label></div><p id="count" class="metrics"></p><div class="history-table-wrap"><table class="history-table"><thead></thead><tbody></tbody></table></div>`;
  const c=views.history.querySelector("#category");categories().forEach((x,i)=>c.add(new Option(`分野${i+1} ${x.title}`,x.categoryId)));[c,views.history.querySelector("#status"),views.history.querySelector("#sort")].forEach((el)=>{el.value=state.history[el.id];el.onchange=()=>{state.history.category=c.value;state.history.status=views.history.querySelector("#status").value;state.history.sort=views.history.querySelector("#sort").value;populateHistory();};});views.history.querySelector("#back").onclick=()=>setView("top");populateHistory(); }
function populateHistory() { let rows=categories().flatMap((category)=>sortedQuestions(category).map((question)=>({category,question}))).filter(({category,question})=>{const result=state.progress.records[String(question.id)]?.lastResult||"unanswered";return (state.history.category==="all"||category.categoryId===state.history.category)&&(state.history.status==="all"||result===state.history.status);}); rows.sort((a,b)=>{const aa=state.progress.records[String(a.question.id)]?.attempts||0,bb=state.progress.records[String(b.question.id)]?.attempts||0;if(state.history.sort==="attempts-desc")return bb-aa||a.question.id-b.question.id;if(state.history.sort==="attempts-asc")return aa-bb||a.question.id-b.question.id;return a.question.id-b.question.id;});const max=Math.max(1,...rows.map(({question})=>state.progress.records[String(question.id)]?.attempts||0)), table=views.history.querySelector(".history-table");views.history.querySelector("#count").textContent=`該当 ${rows.length}問 / 全${allQuestions().length}問`;table.querySelector("thead").innerHTML=`<tr><th class="history-sticky-column">問題</th>${Array.from({length:max},(_,i)=>`<th>${i+1}回目</th>`).join("")}</tr>`;const body=table.querySelector("tbody");body.innerHTML="";rows.forEach(({category,question})=>{const record=state.progress.records[String(question.id)],row=document.createElement("tr"),label=document.createElement("th");label.className="history-sticky-column";const b=document.createElement("button");b.className="history-question";b.textContent=`分野${categoryIndex(category)} 問${question.id} ${question.text.slice(0,15)}`;b.onclick=()=>startReview([question]);label.append(b);row.append(label);for(let i=0;i<max;i++){const cell=document.createElement("td"),entry=record?.history[i];if(entry){cell.textContent=entry.correct?"○":"✕";cell.className=entry.correct?"history-correct":"history-incorrect";}row.append(cell);}body.append(row);}); }

function renderData() { views.data.innerHTML=`<div class="top-header"><h1 id="data-title">データ管理</h1><button class="text-link" id="back">トップに戻る</button></div><div class="data-card"><h2>問題データ（questions.json）を読み込む</h2><label class="file-button">ファイルを選択<input id="questions-file" type="file" accept="application/json,.json"></label><p class="help-text">問題データは端末内にのみ保存されます。買い替えやデータ消去の際は再読み込みが必要です。</p><p id="load-status" class="status-message"></p><p id="load-error" class="error-message" role="alert"></p></div><div class="data-card"><h2>学習記録をエクスポート（保存）</h2><button id="export">学習記録をエクスポート（保存）</button><p class="help-text">iPhoneでは「ファイル」アプリやiCloud Driveへ保存してください。別の端末でインポートすると学習記録を引き継げます。</p></div><div class="data-card"><h2>学習記録をインポート（読み込み）</h2><label class="file-button">ファイルを選択<input id="import" type="file" accept="application/json,.json"></label><p class="help-text">現在の記録は失われます。必要なら先にエクスポートしてください。</p></div><div class="data-card"><h2>学習記録をすべてリセット</h2><button class="secondary" id="reset">学習記録をすべてリセット</button><p class="help-text">すべての学習記録を削除します。この操作は取り消せません。</p></div><div class="data-card"><h2>利用上の注意</h2><p class="help-text">iPhoneでは、ホーム画面に追加してご利用ください。学習記録が消えにくくなります。</p><p class="help-text">学習記録はブラウザ内に保存されます。週に一度はエクスポートして保管することをおすすめします。</p></div><p id="progress-status" class="status-message"></p><p id="progress-error" class="error-message" role="alert"></p>`;views.data.querySelector("#back").onclick=()=>setView("top");views.data.querySelector("#questions-file").onchange=handleQuestionFile;views.data.querySelector("#export").onclick=exportProgress;views.data.querySelector("#import").onchange=importProgress;views.data.querySelector("#reset").onclick=resetProgress; }
function fileError(message) { const el=state.view==="data"?views.data.querySelector("#load-error"):views.top.querySelector("#error");el.textContent=message; }
function handleQuestionFile(event) { const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{let parsed;try{parsed=JSON.parse(reader.result);}catch(_){fileError("JSONを読み込めませんでした。ファイル内容を確認してください。");return;}if(!Array.isArray(parsed.categories)){fileError("問題データに categories 配列がありません。");return;}state.questions=parsed;state.storage.questionsMissing=false;localStorage.setItem(STORAGE_KEYS.questions,JSON.stringify(parsed));const message=`${parsed.categories.length}分野／${allQuestions().length}問を読み込みました。`;if(state.view==="data"){views.data.querySelector("#load-status").textContent=message;views.data.querySelector("#load-error").textContent="";}else setView("top");};reader.onerror=()=>fileError("ファイルを読み込めませんでした。");reader.readAsText(file,"UTF-8"); }
async function exportProgress() { const now=new Date().toISOString();state.progress.exportedAt=now;state.progress.lastExportedAt=now;saveProgress();const json=JSON.stringify(state.progress,null,2),status=views.data.querySelector("#progress-status"),error=views.data.querySelector("#progress-error");error.textContent="";try{const file=typeof File==="function"?new File([json],"progress.json",{type:"application/json"}):null;if(file&&navigator.canShare&&navigator.share&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:"progress.json"});status.textContent="学習記録を共有しました。";}else{const url=URL.createObjectURL(new Blob([json],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download="progress.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),0);status.textContent="学習記録をエクスポートしました。";}}catch(_){error.textContent="学習記録をエクスポートできませんでした。";} }
function importProgress(event) { const file=event.target.files?.[0];if(!file)return;if(!confirm("現在の学習記録を上書きします。よろしいですか？")){event.target.value="";return;}const reader=new FileReader();reader.onload=()=>{try{state.progress=JSON.parse(reader.result);state.progress.records ||= {};state.progress.categoryStatus ||= {};state.progress.resumePointer ||= {};state.storage.progressMissing=false;saveProgress();setView("top");}catch(_){views.data.querySelector("#progress-error").textContent="学習記録を読み込めませんでした。ファイル内容を確認してください。";}};reader.onerror=()=>views.data.querySelector("#progress-error").textContent="学習記録を読み込めませんでした。";reader.readAsText(file,"UTF-8"); }
function resetProgress() { if(!confirm("すべての学習記録を削除します。この操作は取り消せません。よろしいですか？"))return;localStorage.removeItem(STORAGE_KEYS.progress);state.progress=initialProgress();state.storage.progressMissing=false;saveProgress();setView("top"); }
async function requestPersistentStorage(){try{if(navigator.storage?.persist)await navigator.storage.persist();}catch(_){}}
restoreState();requestPersistentStorage();setView("top");
